const bcrypt = require("bcryptjs");
const data = {
  users: [
    {
      name: "hsen",
      email: "hazime@gmail.com",
      password: bcrypt.hashSync("hazime18"),
      isAdmin: false,
    },
    {
      name: "hazime",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("hazime18"),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: ["/image/p1.webp", "/image/p1-2.webp", "/image/p1-3.webp"],
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Slim shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: ["/image/p2.jpg", "/image/p2-2.jpg", "/image/p2-3.jpg"],
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: ["/image/p3.jpg", "/image/p3-2.jpg", "/image/p3-3.jpg"],
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Adidas Slim pant",
      slug: "adidas-slim-pant",
      category: "Pants",
      image: ["/image/p1.jpg", "/image/p1-2.jpg", "/image/p1-3.jpg"],
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
module.exports = data;
